modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "thermal_innovation"
version = "${file.jarVersion}"
displayName = "Thermal Innovation"
displayURL = "https://teamcofh.com/"
logoFile = "thermal_innovation.png"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Thermal Technology marches on. Adds Thermal-style tools and equipment!

Contains player-centric power - useful tools, gadgets, and armor.
'''
[[dependencies.thermal_innovation]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_innovation]]
modId = "forge"
mandatory = true
versionRange = "[40.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_innovation]]
modId = "cofh_core"
mandatory = true
versionRange = "[1.6,1.7]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_innovation]]
modId = "thermal"
mandatory = true
versionRange = "[1.6,1.7]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_innovation]]
modId = "thermal_foundation"
mandatory = true
versionRange = "[1.6,1.7]"
ordering = "AFTER"
side = "BOTH"