modLoader = "javafml"
loaderVersion = "[${forge_major_version},)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "thermal_innovation"
version = "${file.jarVersion}"
displayName = "Thermal Innovation"
updateJSONURL = "https://raw.github.com/cofh/version/main/thermal/update_innovation.json"
displayURL = "https://teamcofh.com/"
logoFile = "thermal_innovation.png"
itemIcon = "thermal:flux_drill"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Thermal Technology marches on. Adds Thermal-style tools and equipment!

Contains player-centric power - useful tools, gadgets, and armor.
'''
[[dependencies.thermal_innovation]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_innovation]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_innovation]]
modId = "cofh_core"
mandatory = true
versionRange = "[${cofh_core_version}, ${cofh_core_max_version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_innovation]]
modId = "thermal"
mandatory = true
versionRange = "[9.2, 9.3]"
ordering = "AFTER"
side = "BOTH"