modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "thermal_innovation"
version = "${file.jarVersion}"
displayName = "Thermal Innovation"
updateJSONURL = "https://raw.github.com/cofh/version/master/thermal/update_innovation.json"
displayURL = "https://teamcofh.com/"
logoFile = "thermal_innovation.png"
itemIcon = "thermal:flux_drill"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Thermal Technology marches on. Adds Thermal-style tools and equipment!

Contains player-centric power - useful tools, gadgets, and armor.
'''
[[dependencies.thermal_innovation]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_innovation]]
modId = "forge"
mandatory = true
versionRange = "[43.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_innovation]]
modId = "cofh_core"
mandatory = true
versionRange = "[10.0, 10.1]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_innovation]]
modId = "thermal"
mandatory = true
versionRange = "[10.0, 10.1]"
ordering = "AFTER"
side = "BOTH"